//new

//EM
//import ARO_Title from '@salesforce/label/c.ARO_Title';


const labels = {
    //ARO_Title
    Add: 'Add',
    Edit: 'Edit',
    Save: 'Save',
    New: 'New',
    Change: 'Change',
    Cancel: 'Cancel',
    ChangePassword: 'Change Password',
    ResetPassword: 'Reset Password',
    CurrentPassword: 'Current Password',
    CurrentPasswordPlc: 'Enter Current Password',
    NewPassword: 'New Password',
    NewPasswordPlc: 'Enter New Password',
    RepeatPassword: 'Repeat Password',
    RepeatPasswordPlc: 'Enter Repeat Password',
    UserProfileTitle: 'User Informations',
    AccountInfoTitle: 'Company Informations',
    ChangePasswordTitle: 'Change Password',
    FirstName: 'First Name',
    LastName: 'Last Name',
    Email: 'Email Address',
    Role: 'Role',
    RolePlc: 'Select Role',
    FirstNamePlc: 'Enter First Name',
    LastNamePlc: 'Enter Last Name',
    EmailPlc: 'Enter Email Address',
    Title: 'Title',
    TitlePlc: 'Enter Your Title',
    NotePlc: 'Insert a note',

    Phone:'Phone',
    PhonePlc:'Enter Phone Number',
    Username:'Username',
    UsernamePlc:'Enter Username',
    City:'City',
    CityPlc:'Enter Current City',
    Birthday:'Birthday',
    BirthdayPlc:'Enter Birthday',
    AboutMe:'About Me',
    AboutMePlc:'Say Something About you! ',
    CompanyName:'Name',
    NumberOfEmployees:'Number Of Employees',
    Website:'Website',
    Phone:'Phone',
    About:'About',
    YearStarted:'Year Started',
    Industry:'Industry',
    Role:'Role',
    Company: 'Company',
    Description: 'Description',
    DescriptionPlc: 'Enter Your Description',
    AddressedTo: 'Addressed To',
    Status : 'Status',
    StartDate: 'Start date',
    EndDate: 'End date',
    AddressedCc: 'Addressed Cc',
    ComplainOn: 'Complain On',
    Note: 'Reason',
    RequestTypeName: 'Request Type',
    ComplainOn: 'Complain On',
    Come: 'Submit by',
    DateLb: 'Date',
    DatePlc: 'Enter Your Date',
    Visibility: 'Public ?',



    Activate: 'Activate',
    Freeze: 'Freeze',
    Disable: 'Disable',
    Delete: 'Delete',
    Group: 'Group',
    SaveAndActive: 'Save And Active',
    Back: 'Back',
    IsPublic: 'Is Public',
    Submiter: 'Submit By',
    StatusPlc: 'Select one status',

    Name: 'Name',
    GroupeMember: 'The Groupe Member are',
    Leader: 'Leader Name',

    PromoteBaseUser: 'Mark As Team Leader',
    
    Submit:'Submit',
    Delete:'Delete',
    Approve:'Approve',

    Submited:'Submited',
    Delete:'Delete',
    Approved:'Approved',
    Draft:'Draft',
    Reject:'Reject',
    SaveandSubmited:'Save and Submit',
    Deleterequest:'Delete request',
    Clonerequest: 'Clone request',
    Editrequest: 'Edit request',
    Sendrequest: 'Send request',
    Createrequest:'Create request',

    FilterTitle: 'Filter the news',
    ConfigTitle: 'News configuration',
    UploadFile: 'Upload File',
    FilterAccomplishment: 'Filter Accomplishment',
    
    label: 'Field Label',
    value: 'Field Value',
    userInfoHlp : 'View user details',
    userEditHlp : 'Edit user details',
    moreInfo:'More Informations',
    
    userMoreInfoHlp : 'More details',
    userEditMoreHlp : 'Edit additionnal information about you , check each time you edit an information. then save all...',
    successOp:'Succes operation',
    errorOp:'Something goes wrong',
    warningOp:'Warning',
    rmvfield:'Field removed',
    addfield:'Field Adjusted',
    
    Supervisor:'Supervisor',
    myprojects:'My Projects (#NB)',
    mytimesheets:'My Timesheets (#NB)',
    myleadedGroups:'My Leaded Groups (#NB)',
    myleadedProjects:'My Leaded Projects (#NB)',
    About: 'About',
    
    projects:'Projects (#NB)',
    timesheets:'Timesheets (#NB)',
    leadedGroups:'Leaded Groups (#NB)',
    leadedProjects:'Leaded Projects (#NB)',
    ok_confirm:'Yes, I\'m sure',
    disable_confirm:'Are you sure you want to disable this User?',
    reset_confirm:'Are you sure you want to reset this user Password?',
    action_confirm:' Action Confirmation',
};
export { labels }