//new

//EM
//import ARO_Title from '@salesforce/label/c.ARO_Title';


const labels = {
    //ARO_Title
    Add: 'Add',
    Edit: 'Edit',
    Save: 'Save',
    New: 'New',
    Change: 'Change',
    Cancel: 'Cancel',
    ChangePassword: 'Change Password',
    ResetPassword: 'Reset Password',
    CurrentPassword: 'Current Password',
    CurrentPasswordPlc: 'Enter Current Password',
    NewPassword: 'New Password',
    NewPasswordPlc: 'Enter New Password',
    RepeatPassword: 'Repeat Password',
    RepeatPasswordPlc: 'Enter Repeat Password',
    UserProfileTitle: 'User Informations',
    AccountInfoTitle: 'Company Informations',
    ChangePasswordTitle: 'Change Password',
    FirstName: 'First Name',
    LastName: 'Last Name',
    Email: 'Email Address',
    Role: 'Role',
    RolePlc: 'Select Role',
    FirstNamePlc: 'Enter First Name',
    LastNamePlc: 'Enter Last Name',
    EmailPlc: 'Enter Email Address',
    Title: 'Title',
    TitlePlc: 'Enter Your Title',
    NotePlc: 'Insert a note',

    Phone:'Phone',
    PhonePlc:'Enter Phone Number',
    Username:'Username',
    UsernamePlc:'Enter Username',
    City:'City',
    CityPlc:'Enter Current City',
    Birthday:'Birthday',
    BirthdayPlc:'Enter Birthday',
    AboutMe:'About Me',
    AboutMePlc:'Say Something About you! ',
    CompanyName:'Name',
    NumberOfEmployees:'Number Of Employees',
    Website:'Website',
    Phone:'Phone',
    About:'About',
    YearStarted:'Year Started',
    Industry:'Industry',
    Role:'Role',
    Company: 'Company',
    Description: 'Description',
    DescriptionPlc: 'Enter Your Description',
    AddressedTo: 'Addressed To',
    Status : 'Status',
    StartDate: 'Start date',
    EndDate: 'End date',
    AddressedCc: 'Addressed Cc',
    ComplainOn: 'Complain On',
    Note: 'Reason',
    RequestTypeName: 'Request Type',
    ComplainOn: 'Complain On',
    Come: 'Submit by',
    DateLb: 'Date',
    DatePlc: 'Enter Your Date',
    Visibility: 'Public ?',



    Activate: 'Activate',
    Freeze: 'Freeze',
    Disable: 'Disable',
    Delete: 'Delete',
    Group: 'Group',
    SaveAndActive: 'Save And Active',
    Back: 'Back',
    IsPublic: 'Is Public',
    Submiter: 'Submit By',
    StatusPlc: 'Select one status',

    Name: 'Name',
    GroupeMember: 'The Groupe Member are',
    Leader: 'Leader Name',

    PromoteBaseUser: 'Mark As Team Leader',
    
    Submit:'Submit',
    Delete:'Delete',
    Approve:'Approve',

    Submited:'Submited',
    Delete:'Delete',
    Approved:'Approved',
    Draft:'Draft',
    Reject:'Reject',
    SaveandSubmited:'Save and Submit',
    Deleterequest:'Delete request',
    Clonerequest: 'Clone request',
    Editrequest: 'Edit request',
    Sendrequest: 'Send request',
    Createrequest:'Create request',
    CreatedDate: 'Created date',
    FilterRequest: 'Filter Request',

    FilterTitle: 'Filter the news',
    ConfigTitle: 'News configuration',
    UploadFile: 'Upload File',
    FilterAccomplishment: 'Filter Accomplishment',
    
    label: 'Field Label',
    value: 'Field Value',
    userInfoHlp : 'View user details',
    userEditHlp : 'Edit user details',
    moreInfo:'More Informations',
    
    userMoreInfoHlp : 'More details',
    userEditMoreHlp : 'Edit additionnal information about you , check each time you edit an information. then save all...',
    successOp:'Succes operation',
    errorOp:'Something goes wrong',
    warningOp:'Warning',
    rmvfield:'Field removed',
    addfield:'Field Adjusted',
    
    Supervisor:'Supervisor',
    myprojects:'My Projects (#NB)',
    mytimesheets:'My Timesheets (#NB)',
    myleadedGroups:'My Leaded Groups (#NB)',
    myleadedProjects:'My Leaded Projects (#NB)',
    About: 'About',
    
    projects:'Projects (#NB)',
    timesheets:'Timesheets (#NB)',
    leadedGroups:'Leaded Groups (#NB)',
    leadedProjects:'Leaded Projects (#NB)',
    ok_confirm:'Yes, I\'m sure',
    disable_confirm:'Are you sure you want to disable this User?',
    reset_confirm:'Are you sure you want to reset this user Password?',
    action_confirm:' Action Confirmation',

    //projects labels
    NewProject:'New Project',
    AvaibleMembers:'Avaible Members',
    SelectedMembers:'Selected Members',
    AddorRemoveProject:'Add or Remove members to the Project',
    DownloadAttachment:'Download Attachment file',
    EditMembers:'Edit Members',
    ProjectDetails:'Project Details',
    ADDAttachment:'ADD Attachment',
    Close:'Close',
    Next:'Next',
    Name:'Name',
    Manager:'Manager',
    Link:'Link',
    Task:'Add Task',
    TaskList:'Task',
    AssignTo:'Asign To',
    AssignToPh:'Select member',
    TaskPh:'Enter your Task Name',
    TaskDescr:'Enter your Task Description',
    Priority:'Priority',
    ProjectMembers:'Project Members',
    ManageTask:'Manage Task',

    // News Label
    AddNews: "Add News",
    Interval : 'Set Interval',
    IntervalPlc :'Enter Interval',
    NewsDelete : 'the news has been successfully deleted',
    NewsDeactivated : 'the news has been successfully deactivated',
    NewsActivated : 'the news has been successfully activated',
    SaveConfiguration : 'Your configuration has been successfully saved',
    UpdateNewsError : 'The record has not been updated ',
    InvalidField: 'The field Is not valid',
    UpdateNews : 'the news has been successfully Update ',
    FileUpdate : 'The file has not been updated',
    DeleteNews_Confirm: 'Are you sure you want to delete this News?',
    DeleteNews_Title : 'Confirm Deletion',
    Reset: 'Reset',

    // Event Label
    Start:'Start',
    End: 'End',
    AddNews: "Add News",
    DeleteFile : 'Delete File',
    ContactName: 'Contact Name',
    StartDatePlc: 'Enter the Start date',
    EndDatePlc: 'Enter the End date',
    NamePlc: 'Enter Name',
    SaveAndSend: 'Save And Send',
    Update: 'Update',
    UpdateAndSend: 'Update And Send',
    Send: 'Send',
    AddNewEvent: 'Add New Event',
    UpdateEvent: 'Update Event',
    PermissionDelete: 'Are you sure to want to delete it ?',
    PermissionRejected: 'Are you sure to want to reject it ?',
    EventDetails: 'Event Details',
    Download: 'Download',
    FileName: 'File Name',
//invoices: 

    new_invoice:'New Invoice',
    new_account:'New Client Account',
    po:'Po',
    invoice_to:"Invoice To",

    //timesheet
    Entries:'Entries',
    Number: 'Number',
    From: 'From',
    To: 'To',
    OrderBy:'sort By',
    selectPlc:'Select an option',
    OrderOn:'As',
    noTimesheet:'No timesheet founded',
};
export { labels }