public  class RH_Constans {
    public static final String RH_CONTACT_RT =Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('RH_USER').getRecordTypeId();
    public static final String RH_PROFILE_NAME ='Custom Identity User';
    public static final String ORG_NAME ='rh-dev';
    public static final String ACTIVATED_WORKGROUP_STATUS ='Activated';
    public RH_Constans() {

    }


}